export const ACTION_CHANGE_SHOW = 'ACTION_CHANGE_SHOW';
export const ACTION_CHANGE_SLIDER = 'ACTION_CHANGE_SLIDER';
export const ACTION_CHANGE_CITY_AUTOCOMPLETE = 'ACTION_CHANGE_CITY_AUTOCOMPLETE';
export const ACTION_CHANGE_POINT_AUTOCOMPLETE = 'ACTION_CHANGE_POINT_AUTOCOMPLETE';